from typing import cast
from langchain.tools import ToolRuntime, tool
import pandas as pd
from os import environ

from api.ai.models import RecommendCoursesContext

courses_csv_path = environ.get("COURSES_CSV_PATH")
if courses_csv_path is None:
    raise ValueError("COURSES_CSV_PATH environment variable is not set.")

courses_df = pd.read_csv(courses_csv_path)

# TODO: I think returning the course name is not enough.
# currently the data generated by omar's script doesn't contain an id,
# if we do add one later, we can just return the course id here,
# and add a tool to get course details by id.


@tool
def get_available_courses(runtime: ToolRuntime[RecommendCoursesContext]) -> list[str]:
    """
    This tool is used to get the available courses for a specific department and academic year.
    The tool will return a list of courses that are available for the user to take based on their department, and completed courses.
    """

    department = runtime.context.department
    completed_courses = runtime.context.completed_courses

    department_courses = cast(
        pd.DataFrame, courses_df[courses_df["department"] == department]
    )

    available_courses = department_courses[
        ~department_courses["course_name"].isin(completed_courses)
    ]

    return available_courses["course_name"].tolist()
