from langchain.tools import ToolRuntime, tool
import pandas as pd
from os import environ
from dotenv import load_dotenv

load_dotenv()
from .schemas import RecommendCoursesContext

knowledge_base_csv_path = environ.get("KNOWLEDGE_BASE_CSV_PATH")
if knowledge_base_csv_path is None:
    raise ValueError("KNOWLEDGE_BASE_CSV_PATH environment variable is not set.")

courses_df = pd.read_csv(knowledge_base_csv_path)

# TODO: I think returning the course name is not enough.
# currently the data generated by omar's script doesn't contain an id,
# if we do add one later, we can just return the course id here,
# and add a tool to get course details by id.


@tool
def get_available_courses(runtime: ToolRuntime[RecommendCoursesContext]) -> list[str]:
    """
    This tool is used to get the available courses for a user. It takes no arguments.
    The tool will return a list of courses that are available for the user to take.
    """

    department = runtime.context.department
    completed_courses = runtime.context.completed_courses

    in_department = courses_df["department"] == department
    not_completed = ~courses_df["course_name"].isin(completed_courses)
    no_prerequisite = courses_df["prerequisite"] == "None"
    prerequisite_completed = courses_df["prerequisite"].isin(completed_courses)

    available_courses = courses_df[
        in_department & not_completed & (no_prerequisite | prerequisite_completed)
    ]

    return str(available_courses["course_name"].tolist())
